CREATE TABLE "coin" (
    ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    DATETIME TIMESTAMP NOT NULL,
    PRICE NUMERIC(20,2) NOT NULL,
    QUANTITY NUMERIC(20,10) NOT NULL
);